| 04-29 00:09:52 | com.djrapitops.plan.BukkitServerShutdownSave caught DBInitException
| 04-29 00:09:58 | com.djrapitops.plan.exceptions.database.DBInitException: Failed to set-up HikariCP Datasource: Failed to initialize pool: Data source rejected establishment of connection,  message from server: "Too many connections"
| 04-29 00:09:58 |    com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:122)
| 04-29 00:09:58 |    com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:108)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ServerShutdownSave.saveActiveSessions(ServerShutdownSave.java:108)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ServerShutdownSave.attemptSave(ServerShutdownSave.java:91)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ServerShutdownSave.performSave(ServerShutdownSave.java:85)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ShutdownHook.run(ShutdownHook.java:69)
| 04-29 00:09:58 | Caused by:
| 04-29 00:09:58 | plan.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Data source rejected establishment of connection,  message from server: "Too many connections"
| 04-29 00:09:58 |    plan.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:589)
| 04-29 00:09:58 |    plan.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:575)
| 04-29 00:09:58 |    plan.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
| 04-29 00:09:58 |    plan.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
| 04-29 00:09:58 |    com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:120)
| 04-29 00:09:58 |    com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:108)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ServerShutdownSave.saveActiveSessions(ServerShutdownSave.java:108)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ServerShutdownSave.attemptSave(ServerShutdownSave.java:91)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ServerShutdownSave.performSave(ServerShutdownSave.java:85)
| 04-29 00:09:58 |    com.djrapitops.plan.gathering.ShutdownHook.run(ShutdownHook.java:69)
| 04-29 00:09:58 | Caused by:
| 04-29 00:09:58 | com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
| 04-29 00:09:58 |    sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| 04-29 00:09:58 |    sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
| 04-29 00:09:58 |    sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| 04-29 00:09:58 |    java.lang.reflect.Constructor.newInstance(Constructor.java:423)
| 04-29 00:09:58 |    com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
| 04-29 00:09:58 |    com.mysql.jdbc.Util.getInstance(Util.java:382)
| 04-29 00:09:58 |    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
| 04-29 00:09:58 |    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
| 04-29 00:09:58 |    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
| 04-29 00:09:58 |    com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1116)
| 04-29 00:09:58 |    com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
| 04-29 00:10:05 |    com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
| 04-29 00:10:05 |    com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
| 04-29 00:10:05 |    com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
| 04-29 00:10:05 |    com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
| 04-29 00:10:05 |    sun.reflect.GeneratedConstructorAccessor100.newInstance(Unknown Source)
| 04-29 00:10:05 |    sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| 04-29 00:10:05 |    java.lang.reflect.Constructor.newInstance(Constructor.java:423)
| 04-29 00:10:05 |    com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
| 04-29 00:10:05 |    com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
| 04-29 00:10:05 |    com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
| 04-29 00:10:05 |    plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
| 04-29 00:10:05 |    plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
| 04-29 00:10:05 |    plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
| 04-29 00:10:05 |    plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
| 04-29 00:10:05 |    plan.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
| 04-29 00:10:05 |    plan.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
| 04-29 00:10:05 |    plan.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
| 04-29 00:10:05 |    com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:120)
| 04-29 00:10:05 |    com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:108)
| 04-29 00:10:05 |    com.djrapitops.plan.gathering.ServerShutdownSave.saveActiveSessions(ServerShutdownSave.java:108)
| 04-29 00:10:05 |    com.djrapitops.plan.gathering.ServerShutdownSave.attemptSave(ServerShutdownSave.java:91)
| 04-29 00:10:05 |    com.djrapitops.plan.gathering.ServerShutdownSave.performSave(ServerShutdownSave.java:85)
| 04-29 00:10:05 |    com.djrapitops.plan.gathering.ShutdownHook.run(ShutdownHook.java:69)
